In [1]:
import numpy as np
import pandas as pd
from scipy import stats
from utils import get_data, save_data, get_test_preds, add_intervals_to_test, all_tests, save_param_values, get_race_info 
from plots import plots_for_race, plot_interval_checks
np.random.seed(2025)

race = "bos"
size1, size2 = 24000, 20000
train_yr, test_yr = [2021, 2022, 2023], [2024]

save_data(race_list=["bos", "nyc", "chi"], size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr)
train, test = get_data(racename=race, size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr, save=False)
params = save_param_values(race)
get_race_info()

models, baseline = ["M1", "M2", "M3"], "BL"
test_preds = get_test_preds(test, race, baseline=baseline, full=False)
test_preds

,id,dist,curr_pace,total_pace,finish,age,gender,year,male,alpha,age_t,agegroup,lvl,BL,M1,M2,M3
11773,77411,5K,3.238342,3.238342,3.201199,46,F,2024,0,1,0.46,3,1,-2.519733,10.710485,9.655934,10.347371
14516,80154,5K,3.649635,3.649635,3.030162,56,F,2024,0,1,0.56,4,1,-39.392833,-29.457334,-30.489017,-28.396109
4385,70023,5K,4.111842,4.111842,3.720571,36,M,2024,1,1,0.36,2,1,-17.986267,-10.561189,-11.549633,-10.759539
17258,82896,5K,3.373819,3.373819,2.833591,49,M,2024,1,1,0.49,3,1,-39.740033,-27.740310,-28.789964,-26.683053
23673,89311,5K,2.554931,2.554931,2.180507,30,F,2024,0,1,0.30,2,1,-47.264617,-24.192148,-25.181547,-29.372974
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190181,78985,40K,2.645503,3.111872,3.103030,37,F,2024,0,1,0.37,2,8,-0.643946,0.042443,1.100990,1.066255
192506,81310,40K,2.862049,2.957705,2.954004,58,F,2024,0,1,0.58,4,8,-0.297842,0.434638,-0.065947,0.208620
186340,75144,40K,2.930832,3.383808,3.345889,37,M,2024,1,1,0.37,2,8,-2.355377,-1.738048,-0.865355,-0.876504
190297,79101,40K,3.158560,3.088326,3.096199,57,M,2024,1,1,0.57,4,8,0.579017,1.272083,0.153769,0.377782
179862,68666,40K,3.828484,3.883118,3.882499,30,F,2024,0,1,0.30,2,8,-0.028877,0.491254,0.156117,0.107626

In [2]:
# import matplotlib.pyplot as plt
# pd.read_csv("stan_results/model2/params_bos.csv").describe().T
# params_tbl = pd.read_csv("analysis/tables/bos_params.csv")
# for col in params_tbl.columns:
#   if 'mean' in col:
#     plt.plot(params_tbl[col], label=col)

# # plt.plot(params_tbl["total_pace_mean"] + params_tbl["curr_pace_mean"])
# # plt.plot(params_tbl["total_pace_mean"] + params_tbl["curr_pace_mean"]+ params_tbl["alpha_mean"])
# plt.legend()
# plt.show()
# # plt.plot(pd.read_csv("analysis/tables/bos_params.csv")["curr_pace"])
# params_tbl["alpha_mean"]# + params_tbl["curr_pace_mean"]

In [3]:
test_list = [["BL", "M1"], ["BL", "M2"], ["BL", "M3"],["M1", "M2"], ["M1", "M3"], ["M2", "M3"]]
tbl2 = all_tests(test_preds, test_list, savename=f"analysis/tables/{race}_stattest.csv")
print(tbl2)

comp_model = "M3"
error_tbl = plots_for_race(test_preds, race, models, baseline, comp_model)
error_tbl

/Users/brandononyejekwe/Documents/Personal_Projects/Marathon_Predictor/utils.py:254: UserWarning: p-value floored: true value smaller than 0.001. Consider specifying `method` (e.g. `method=stats.PermutationMethod()`.)
  value = stats.anderson_ksamp([arr1, arr2]).pvalue

            KS Wilcoxon      CVM     AD
BL-M1  <0.0001  <0.0001  <0.0001  0.001
BL-M2  <0.0001  <0.0001  <0.0001  0.001
BL-M3  <0.0001  <0.0001  <0.0001  0.001
M1-M2  <0.0001  <0.0001  <0.0001  0.001
M1-M3  <0.0001  <0.0001  <0.0001  0.001
M2-M3  <0.0001  <0.0001  <0.0001  0.001
File saved: analysis/plots/bos_error_bar.jpg
File saved: analysis/tables/bos_error.csv
File saved: analysis/plots/bos_error_groups.jpg
File saved: analysis/plots/bos_error_gender_age.jpg

,BL,M1,M2,M3,pcnt_M1,pcnt_M2,pcnt_M3
5K,24.431269,15.845393,16.284039,15.732155,0.351430,0.333476,0.356065
10K,22.890636,14.161318,13.441081,12.929037,0.381349,0.412813,0.435182
15K,20.833577,12.117128,11.300180,10.732988,0.418385,0.457598,0.484823
20K,18.622429,10.741829,9.358181,8.958194,0.423178,0.497478,0.518957
25K,14.777327,8.329777,6.821183,6.595969,0.436314,0.538402,0.553643
30K,10.392143,6.364822,4.449005,4.408976,0.387535,0.571888,0.575739
35K,5.229800,3.723508,2.565699,2.592794,0.288021,0.509408,0.504227
40K,1.252623,1.041800,0.740674,0.714535,0.168306,0.408701,0.429569
Overall MAE,14.828000,9.048000,8.122000,7.834000,NaN,NaN,NaN
Overall $R^2$,0.787000,0.896000,0.899000,0.905000,NaN,NaN,NaN

In [4]:
# import pandas as pd
# params = pd.read_csv(f"stan_results/model3/params_{race}.csv", index_col="Unnamed: 0")
# params.describe().T[["mean", "std", "25%", "50%", "75%"]].round(4)

In [5]:
# train_full, test_full = get_data(racename=race, size_train=None, size_test=None, train_lis=train_yr, test_lis=test_yr, save=False)
# print(stats.ks_2samp(train["finish"], train_full["finish"]).pvalue)
# print(stats.anderson_ksamp([train["finish"], train_full["finish"]]).pvalue)
# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)
# print(stats.anderson_ksamp([test["finish"], test_full["finish"]]).pvalue)

# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)
# print(stats.ks_2samp(test["curr_pace"], test_full["curr_pace"]).pvalue)
# print(stats.ks_2samp(test["total_pace"], test_full["total_pace"]).pvalue)
# print(stats.ks_2samp(test["age"], test_full["age"]).pvalue)
# print(stats.ks_2samp(test["male"], test_full["male"]).pvalue)

In [6]:
mpreds2 = get_test_preds(test, race, baseline=baseline, full=True)
intervals_tbl = add_intervals_to_test(test_preds, mpreds2, models)
i_check, i_sizes = plot_interval_checks(intervals_tbl, models, save_name=race)

File saved: analysis/plots/bos_intervals
analysis/tables/bos_intsizes.csv
analysis/tables/bos_intcheck.csv