In [1]:
import numpy as np
import pandas as pd
from scipy import stats
from utils import get_data, save_data, get_test_preds, add_intervals_to_test, all_tests, save_param_values, get_race_info 
from plots import plots_for_race, plot_interval_checks
np.random.seed(2025)

race = "full"
size1, size2 = 5000, 5000
train_yr, test_yr = [2021, 2022, 2023], [2024]

# save_data(race_list=["bos", "nyc", "chi"], size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr)
# train, test = get_data(racename=race, size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr, save=False)
train, test = get_data(size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr, save=False)
test = test.sort_values(["lvl", "Race"]).reset_index()
# params = save_param_values(race, rnd=3)
# get_race_info()

models, baseline = ["M1", "M2", "M3", "M4", "M5"], "BL"
test_preds = get_test_preds(test, race, baseline=baseline, full=False)
test_preds

,index,id,dist,curr_pace,total_pace,finish,age,gender,year,male,...,Race,race_bos,race_chi,race_nyc,BL,M1,M2,M3,M4,M5
0,24639,90277,5K,2.917153,2.917153,2.035161,56,F,2024,0,...,bos,1,0,0,-104.475900,-87.096525,-88.248534,-86.977524,-88.200494,-88.187971
1,18532,84170,5K,3.099814,3.099814,2.725423,50,F,2024,0,...,bos,1,0,0,-31.164883,-15.608320,-17.179611,-15.519263,-17.141716,-17.135011
2,10089,75727,5K,3.422313,3.422313,3.306559,47,F,2024,0,...,bos,1,0,0,-7.193683,5.817086,4.139802,5.867006,4.158831,4.157603
3,5673,71311,5K,3.753754,3.753754,3.602408,61,M,2024,1,...,bos,1,0,0,-7.870867,3.163154,4.913156,3.185311,4.911676,4.923278
4,14739,80377,5K,3.326680,3.326680,3.017377,51,M,2024,1,...,bos,1,0,0,-21.669717,-7.979063,-5.944102,-7.919031,-5.917586,-5.891836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,435644,172888,40K,1.524855,1.891342,1.856602,27,M,2024,1,...,nyc,0,0,1,-6.957477,-5.737282,-5.030498,-4.737653,-4.970417,-4.973237
14996,398188,135432,40K,2.965599,3.061615,3.050535,29,W,2024,0,...,nyc,0,0,1,-0.834302,-0.089054,-0.510486,-0.712795,-0.914415,-0.912787
14997,427045,164289,40K,2.068680,2.250605,2.241077,48,W,2024,0,...,nyc,0,0,1,-1.328444,-0.307879,-0.764641,-0.845591,-0.878819,-0.877449
14998,430954,168198,40K,1.880406,2.105928,2.098627,26,W,2024,0,...,nyc,0,0,1,-1.161738,-0.069185,-0.773327,-0.344597,-0.873915,-0.872629
14999,434098,171342,40K,1.797268,1.955799,1.957732,26,M,2024,1,...,nyc,0,0,1,0.355058,1.533887,2.166419,0.642506,0.435817,0.432081

In [ ]:
# params = pd.read_csv(f"stan_results/params_full3.csv", index_col="Unnamed: 0")
# params.describe().T[["mean", "std", "25%", "50%", "75%"]].round(4)

# import matplotlib.pyplot as plt
# params_tbl = pd.read_csv("analysis/tables/bos_params.csv")
# for col in params_tbl.columns:
#   if 'mean' in col:
#     plt.plot(params_tbl[col], label=col)

# # plt.plot(params_tbl["total_pace_mean"] + params_tbl["curr_pace_mean"])
# # plt.plot(params_tbl["total_pace_mean"] + params_tbl["curr_pace_mean"]+ params_tbl["alpha_mean"])
# plt.legend()
# plt.show()
# # plt.plot(pd.read_csv("analysis/tables/bos_params.csv")["curr_pace"])
# params_tbl["alpha_mean"]# + params_tbl["curr_pace_mean"]

In [12]:
sname = "full"
models, baseline = ["M1", "M2", "M3", "M4", "M5"], "BL"
ttest_preds = test_preds#[test_preds["Race"] == sname]
test_list = [["BL", "M1"], ["BL", "M2"], ["BL", "M3"],["M1", "M2"], ["M1", "M3"], ["M2", "M3"]]
tbl2 = all_tests(ttest_preds, test_list, savename=f"analysis/tables/{race}_stattest.csv")
print(tbl2)

comp_model = "M3"
error_tbl = plots_for_race(ttest_preds, race + sname, models, baseline, comp_model)
error_tbl

/Users/brandononyejekwe/Documents/Personal_Projects/Marathon_Predictor/utils.py:296: UserWarning: p-value floored: true value smaller than 0.001. Consider specifying `method` (e.g. `method=stats.PermutationMethod()`.)
  value = stats.anderson_ksamp([arr1, arr2]).pvalue

            KS Wilcoxon      CVM      AD
BL-M1  <0.0001  <0.0001  <0.0001  0.0010
BL-M2  <0.0001  <0.0001  <0.0001  0.0010
BL-M3  <0.0001  <0.0001  <0.0001  0.0010
M1-M2   0.0287  <0.0001    0.048  0.0757
M1-M3  <0.0001  <0.0001  <0.0001  0.0010
M2-M3  <0.0001  <0.0001  <0.0001  0.0010
File saved: analysis/plots/fullfull_error_bar.jpg
File saved: analysis/tables/fullfull_error.csv
File saved: analysis/plots/fullfull_error_groups.jpg
File saved: analysis/plots/fullfull_error_gender_age.jpg

,BL,M1,M2,M3,M4,M5,pcnt_M1,pcnt_M2,pcnt_M3,pcnt_M4,pcnt_M5
5K,22.134553,16.894346,16.742597,16.885951,16.734581,16.733394,0.236743,0.243599,0.237123,0.243961,0.244015
10K,20.637726,15.439464,15.260909,14.358783,14.260514,14.257835,0.251882,0.260533,0.304246,0.309007,0.309137
15K,19.180675,13.548932,13.265577,12.173591,11.944977,11.948648,0.293616,0.308388,0.365320,0.377239,0.377048
20K,16.873706,11.207482,11.002653,9.104193,8.915422,8.914910,0.335802,0.347941,0.460451,0.471638,0.471668
25K,13.179130,9.167562,8.901517,6.812398,6.688298,6.688912,0.304388,0.324575,0.483092,0.492508,0.492462
30K,9.708875,6.846627,6.651959,4.822555,4.773615,4.773624,0.294807,0.314858,0.503284,0.508325,0.508324
35K,5.226094,3.964003,3.821466,2.563166,2.535083,2.535463,0.241498,0.268772,0.509545,0.514918,0.514845
40K,1.162766,1.086761,1.045807,0.796143,0.766445,0.766336,0.065366,0.100587,0.315302,0.340843,0.340937
Overall MAE,13.499000,9.755000,9.572000,8.423000,8.310000,8.310000,NaN,NaN,NaN,NaN,NaN
Overall $R^2$,0.871000,0.931000,0.932000,0.939000,0.939000,0.939000,NaN,NaN,NaN,NaN,NaN

In [ ]:
# train_full, test_full = get_data(racename=race, size_train=None, size_test=None, train_lis=train_yr, test_lis=test_yr, save=False)
# print(stats.ks_2samp(train["finish"], train_full["finish"]).pvalue)
# # print(stats.anderson_ksamp([train["finish"], train_full["finish"]]).pvalue)
# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)
# print()
# # print(stats.anderson_ksamp([test["finish"], test_full["finish"]]).pvalue)

# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)
# print(stats.ks_2samp(test["curr_pace"], test_full["curr_pace"]).pvalue)
# print(stats.ks_2samp(test["total_pace"], test_full["total_pace"]).pvalue)
# print(stats.ks_2samp(test["age"], test_full["age"]).pvalue)
# print(stats.ks_2samp(test["male"], test_full["male"]).pvalue)

In [11]:
mpreds2 = get_test_preds(test, race, baseline=baseline, full=True)
intervals_tbl = add_intervals_to_test(test_preds, mpreds2, models)
i_check, i_sizes = plot_interval_checks(intervals_tbl, models, save_name=race)

File saved: analysis/plots/full_intervals
analysis/tables/full_intsizes.csv
analysis/tables/full_intcheck.csv