In [1]:
import numpy as np
import pandas as pd
from scipy import stats
from utils import get_data, save_data, get_test_preds, save_param_values, get_race_info 
from plots import tests_and_plots, tests_and_plots_full
np.random.seed(2025)

race = "all"
size1, size2 = 5000, 5000
train_yr, test_yr = [2021, 2022, 2023], [2024]

# save_data(race_list=["bos", "nyc", "chi"], size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr)
# train, test = get_data(racename=race, size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr, save=False)
train, test = get_data(size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr, save=False)
test = test.sort_values(["lvl", "Race"]).reset_index()
# params = save_param_values(race, rnd=3)
# get_race_info()

models, baseline = ["S1", "S2", "S3", "S4", "S5"], "BL"
test_preds = get_test_preds(test, race, baseline=baseline, full=False)
test_preds

,index,id,dist,curr_pace,total_pace,finish,age,gender,year,male,...,Race,race_bos,race_chi,race_nyc,BL,S1,S2,S3,S4,S5
0,24639,90277,5K,2.917153,2.917153,2.035161,56,F,2024,0,...,bos,1,0,0,-104.475900,-87.096525,-88.248534,-86.977524,-88.200494,-88.187971
1,18532,84170,5K,3.099814,3.099814,2.725423,50,F,2024,0,...,bos,1,0,0,-31.164883,-15.608320,-17.179611,-15.519263,-17.141716,-17.135011
2,10089,75727,5K,3.422313,3.422313,3.306559,47,F,2024,0,...,bos,1,0,0,-7.193683,5.817086,4.139802,5.867006,4.158831,4.157603
3,5673,71311,5K,3.753754,3.753754,3.602408,61,M,2024,1,...,bos,1,0,0,-7.870867,3.163154,4.913156,3.185311,4.911676,4.923278
4,14739,80377,5K,3.326680,3.326680,3.017377,51,M,2024,1,...,bos,1,0,0,-21.669717,-7.979063,-5.944102,-7.919031,-5.917586,-5.891836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,435644,172888,40K,1.524855,1.891342,1.856602,27,M,2024,1,...,nyc,0,0,1,-6.957477,-5.737282,-5.030498,-4.737653,-4.970417,-4.973237
14996,398188,135432,40K,2.965599,3.061615,3.050535,29,W,2024,0,...,nyc,0,0,1,-0.834302,-0.089054,-0.510486,-0.712795,-0.914415,-0.912787
14997,427045,164289,40K,2.068680,2.250605,2.241077,48,W,2024,0,...,nyc,0,0,1,-1.328444,-0.307879,-0.764641,-0.845591,-0.878819,-0.877449
14998,430954,168198,40K,1.880406,2.105928,2.098627,26,W,2024,0,...,nyc,0,0,1,-1.161738,-0.069185,-0.773327,-0.344597,-0.873915,-0.872629
14999,434098,171342,40K,1.797268,1.955799,1.957732,26,M,2024,1,...,nyc,0,0,1,0.355058,1.533887,2.166419,0.642506,0.435817,0.432081

In [2]:
models, baseline = ["S1", "S2", "S3", "S4", "S5"], "BL"
races_list = ["all", "bos", "nyc", "chi"]
tests_list = ["KS", "CVM", "Wilcoxon"]
comp_model = "S3"

tables_dict = tests_and_plots(test_data_full=test_preds, races_list=races_list, models=models,
                               baseline=baseline, comp_model=comp_model, tests_list=tests_list)

# print(tables_dict["bos"][0])
tables_dict["bos"][1]

File saved: analysis/tables/all_stattest.csv
File saved: analysis/plots/all_error_bar.jpg
File saved: analysis/tables/all_error.csv
File saved: analysis/plots/all_error_groups.jpg
File saved: analysis/plots/all_error_gender_age.jpg
File saved: analysis/tables/bos_stattest.csv
File saved: analysis/plots/bos_error_bar.jpg
File saved: analysis/tables/bos_error.csv
File saved: analysis/plots/bos_error_groups.jpg
File saved: analysis/plots/bos_error_gender_age.jpg
File saved: analysis/tables/nyc_stattest.csv
File saved: analysis/plots/nyc_error_bar.jpg
File saved: analysis/tables/nyc_error.csv
File saved: analysis/plots/nyc_error_groups.jpg
File saved: analysis/plots/nyc_error_gender_age.jpg
File saved: analysis/tables/chi_stattest.csv
File saved: analysis/plots/chi_error_bar.jpg
File saved: analysis/tables/chi_error.csv
File saved: analysis/plots/chi_error_groups.jpg
File saved: analysis/plots/chi_error_gender_age.jpg

,BL,S1,S2,S3,S4,S5,pcnt_S1,pcnt_S2,pcnt_S3,pcnt_S4,pcnt_S5
5K,24.148802,15.224833,15.099169,15.202999,15.086781,15.080872,0.369541,0.374745,0.370445,0.375258,0.375502
10K,23.942534,15.076187,14.798286,13.625403,13.500184,13.508055,0.370318,0.381925,0.430912,0.436142,0.435813
15K,21.036246,12.007490,11.785960,10.739029,10.614586,10.613778,0.429200,0.439731,0.489499,0.495414,0.495453
20K,17.961882,10.101905,9.960039,8.156305,8.024567,8.022781,0.437592,0.445490,0.545910,0.553245,0.553344
25K,14.923170,8.524884,8.364820,6.655708,6.523323,6.522677,0.428748,0.439474,0.554002,0.562873,0.562916
30K,10.290082,6.414794,6.179037,4.485331,4.418224,4.417684,0.376604,0.399515,0.564111,0.570633,0.570685
35K,5.283297,3.719266,3.639852,2.568521,2.547004,2.547274,0.296033,0.311064,0.513841,0.517914,0.517863
40K,1.188630,0.981370,0.950705,0.721041,0.694731,0.694510,0.174369,0.200168,0.393385,0.415520,0.415705
Overall MAE,14.652000,8.877000,8.720000,7.641000,7.549000,7.549000,NaN,NaN,NaN,NaN,NaN
Overall $R^2$,0.799000,0.904000,0.907000,0.918000,0.920000,0.920000,NaN,NaN,NaN,NaN,NaN

In [3]:
tables_dict2 = tests_and_plots_full(test_data_full=test_preds, races_list=races_list, models=models,
                               baseline=baseline, comp_model=comp_model, tests_list=tests_list)
i_check, i_sizes = tables_dict2["all"]

File saved: analysis/plots/all_intervals
analysis/tables/all_intsizes.csv
analysis/tables/all_intcheck.csv
File saved: analysis/plots/bos_intervals
analysis/tables/bos_intsizes.csv
analysis/tables/bos_intcheck.csv
File saved: analysis/plots/nyc_intervals
analysis/tables/nyc_intsizes.csv
analysis/tables/nyc_intcheck.csv
File saved: analysis/plots/chi_intervals
analysis/tables/chi_intsizes.csv
analysis/tables/chi_intcheck.csv

In [4]:
# train_full, test_full = get_data(racename=race, size_train=None, size_test=None, train_lis=train_yr, test_lis=test_yr, save=False)
# print(stats.ks_2samp(train["finish"], train_full["finish"]).pvalue)
# # print(stats.anderson_ksamp([train["finish"], train_full["finish"]]).pvalue)
# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)
# print()
# # print(stats.anderson_ksamp([test["finish"], test_full["finish"]]).pvalue)

# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)
# print(stats.ks_2samp(test["curr_pace"], test_full["curr_pace"]).pvalue)
# print(stats.ks_2samp(test["total_pace"], test_full["total_pace"]).pvalue)
# print(stats.ks_2samp(test["age"], test_full["age"]).pvalue)
# print(stats.ks_2samp(test["male"], test_full["male"]).pvalue)

In [5]:
# params = pd.read_csv(f"stan_results/params_full3.csv", index_col="Unnamed: 0")
# params.describe().T[["mean", "std", "25%", "50%", "75%"]].round(4)

# import matplotlib.pyplot as plt
# params_tbl = pd.read_csv("analysis/tables/bos_params.csv")
# for col in params_tbl.columns:
#   if 'mean' in col:
#     plt.plot(params_tbl[col], label=col)

# # plt.plot(params_tbl["total_pace_mean"] + params_tbl["curr_pace_mean"])
# # plt.plot(params_tbl["total_pace_mean"] + params_tbl["curr_pace_mean"]+ params_tbl["alpha_mean"])
# plt.legend()
# plt.show()
# # plt.plot(pd.read_csv("analysis/tables/bos_params.csv")["curr_pace"])
# params_tbl["alpha_mean"]# + params_tbl["curr_pace_mean"]