In [1]:
import numpy as np
import pandas as pd
from scipy import stats
from utils import get_data, save_data, get_test_preds, add_intervals_to_test, all_tests, save_param_values, get_race_info 
from plots import plots_for_race, plot_interval_checks
np.random.seed(2025)

race = "full"
size1, size2 = 5000, 5000
train_yr, test_yr = [2021, 2022, 2023], [2024]

# save_data(race_list=["bos", "nyc", "chi"], size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr)
# train, test = get_data(racename=race, size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr, save=False)
train, test = get_data(size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr, save=False)
test = test.sort_values(["lvl", "Race"]).reset_index()
# params = save_param_values(race, rnd=3)
# get_race_info()

models, baseline = ["M1", "M2", "M3"], "BL"
test_preds = get_test_preds(test, race, baseline=baseline, full=False)
test_preds

,index,id,dist,curr_pace,total_pace,finish,age,gender,year,male,...,agegroup,lvl,Race,race_bos,race_chi,race_nyc,BL,M1,M2,M3
0,24639,90277,5K,2.917153,2.917153,2.035161,56,F,2024,0,...,4,1,bos,1,0,0,-104.475900,-87.096525,-86.975719,-88.187971
1,18532,84170,5K,3.099814,3.099814,2.725423,50,F,2024,0,...,4,1,bos,1,0,0,-31.164883,-15.608320,-15.510777,-17.135011
2,10089,75727,5K,3.422313,3.422313,3.306559,47,F,2024,0,...,3,1,bos,1,0,0,-7.193683,5.817086,5.883789,4.157603
3,5673,71311,5K,3.753754,3.753754,3.602408,61,M,2024,1,...,4,1,bos,1,0,0,-7.870867,3.163154,3.207520,4.923278
4,14739,80377,5K,3.326680,3.326680,3.017377,51,M,2024,1,...,4,1,bos,1,0,0,-21.669717,-7.979063,-7.904332,-5.891836
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14995,435644,172888,40K,1.524855,1.891342,1.856602,27,M,2024,1,...,1,8,nyc,0,0,1,-6.957477,-5.737282,-4.735832,-4.973237
14996,398188,135432,40K,2.965599,3.061615,3.050535,29,W,2024,0,...,1,8,nyc,0,0,1,-0.834302,-0.089054,-0.714920,-0.912787
14997,427045,164289,40K,2.068680,2.250605,2.241077,48,W,2024,0,...,3,8,nyc,0,0,1,-1.328444,-0.307879,-0.846789,-0.877449
14998,430954,168198,40K,1.880406,2.105928,2.098627,26,W,2024,0,...,1,8,nyc,0,0,1,-1.161738,-0.069185,-0.345130,-0.872629
14999,434098,171342,40K,1.797268,1.955799,1.957732,26,M,2024,1,...,1,8,nyc,0,0,1,0.355058,1.533887,0.641619,0.432081

In [16]:
ttest_preds = test_preds[test_preds["Race"] == "bos"]
ttest_preds["M1"].hist(bins=50, alpha=0.3)
ttest_preds["BL"].hist(bins=50, alpha=0.3)

In [5]:
# import matplotlib.pyplot as plt
# pd.read_csv("stan_results/model2/params_bos.csv").describe().T
# params_tbl = pd.read_csv("analysis/tables/bos_params.csv")
# for col in params_tbl.columns:
#   if 'mean' in col:
#     plt.plot(params_tbl[col], label=col)

# # plt.plot(params_tbl["total_pace_mean"] + params_tbl["curr_pace_mean"])
# # plt.plot(params_tbl["total_pace_mean"] + params_tbl["curr_pace_mean"]+ params_tbl["alpha_mean"])
# plt.legend()
# plt.show()
# # plt.plot(pd.read_csv("analysis/tables/bos_params.csv")["curr_pace"])
# params_tbl["alpha_mean"]# + params_tbl["curr_pace_mean"]

In [4]:
sname = "bos"
models, baseline = ["M1", "M2", "M3"], "BL"
ttest_preds = test_preds[test_preds["Race"] == sname]
test_list = [["BL", "M1"], ["BL", "M2"], ["BL", "M3"],["M1", "M2"], ["M1", "M3"], ["M2", "M3"]]
tbl2 = all_tests(ttest_preds, test_list, savename=f"analysis/tables/{race}_stattest.csv")
print(tbl2)

comp_model = "M3"
error_tbl = plots_for_race(ttest_preds, race + sname, models, baseline, comp_model)
error_tbl

/Users/brandononyejekwe/Documents/Personal_Projects/Marathon_Predictor/utils.py:290: UserWarning: p-value floored: true value smaller than 0.001. Consider specifying `method` (e.g. `method=stats.PermutationMethod()`.)
  value = stats.anderson_ksamp([arr1, arr2]).pvalue
/Users/brandononyejekwe/Documents/Personal_Projects/Marathon_Predictor/utils.py:290: UserWarning: p-value capped: true value larger than 0.25. Consider specifying `method` (e.g. `method=stats.PermutationMethod()`.)
  value = stats.anderson_ksamp([arr1, arr2]).pvalue

            KS Wilcoxon      CVM     AD
BL-M1  <0.0001  <0.0001  <0.0001  0.001
BL-M2  <0.0001  <0.0001  <0.0001  0.001
BL-M3  <0.0001  <0.0001  <0.0001  0.001
M1-M2  <0.0001  <0.0001  <0.0001  0.001
M1-M3  <0.0001  <0.0001  <0.0001  0.001
M2-M3   0.2392   0.2612   0.3559  0.250
File saved: analysis/plots/fullbos_error_bar.jpg
File saved: analysis/tables/fullbos_error.csv
File saved: analysis/plots/fullbos_error_groups.jpg
File saved: analysis/plots/fullbos_error_gender_age.jpg

,BL,M1,M2,M3,pcnt_M1,pcnt_M2,pcnt_M3
5K,24.148802,15.224833,15.200810,15.080872,0.369541,0.370536,0.375502
10K,23.942534,15.076187,13.634376,13.508055,0.370318,0.430537,0.435813
15K,21.036246,12.007490,10.735564,10.613778,0.429200,0.489663,0.495453
20K,17.961882,10.101905,8.158635,8.022781,0.437592,0.545781,0.553344
25K,14.923170,8.524884,6.653332,6.522677,0.428748,0.554161,0.562916
30K,10.290082,6.414794,4.484079,4.417684,0.376604,0.564233,0.570685
35K,5.283297,3.719266,2.568674,2.547274,0.296033,0.513812,0.517863
40K,1.188630,0.981370,0.721352,0.694510,0.174369,0.393123,0.415705
Overall MAE,14.652000,8.877000,7.642000,7.549000,NaN,NaN,NaN
Overall $R^2$,0.799000,0.904000,0.918000,0.920000,NaN,NaN,NaN

In [7]:
# import pandas as pd
# params = pd.read_csv(f"stan_results/model3/params_{race}.csv", index_col="Unnamed: 0")
# params.describe().T[["mean", "std", "25%", "50%", "75%"]].round(4)

In [8]:
# train_full, test_full = get_data(racename=race, size_train=None, size_test=None, train_lis=train_yr, test_lis=test_yr, save=False)
# print(stats.ks_2samp(train["finish"], train_full["finish"]).pvalue)
# # print(stats.anderson_ksamp([train["finish"], train_full["finish"]]).pvalue)
# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)
# print()
# # print(stats.anderson_ksamp([test["finish"], test_full["finish"]]).pvalue)

# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)
# print(stats.ks_2samp(test["curr_pace"], test_full["curr_pace"]).pvalue)
# print(stats.ks_2samp(test["total_pace"], test_full["total_pace"]).pvalue)
# print(stats.ks_2samp(test["age"], test_full["age"]).pvalue)
# print(stats.ks_2samp(test["male"], test_full["male"]).pvalue)

In [5]:
# mpreds2 = get_test_preds(test, race, baseline=baseline, full=True)
# intervals_tbl = add_intervals_to_test(test_preds, mpreds2, models)
# i_check, i_sizes = plot_interval_checks(intervals_tbl, models, save_name=race)