In [37]:
import numpy as np
import pandas as pd
from scipy import stats
from utils import get_data, save_data, get_test_preds, add_intervals_to_test, all_tests, save_param_values, get_race_info 
from plots import plots_for_race, plot_interval_checks
np.random.seed(2025)

race = "chi"
size1, size2 = 24000, 20000
train_yr, test_yr = [2021, 2022, 2023], [2024]

save_data(race_list=["bos", "nyc", "chi"], size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr)
train, test = get_data(racename=race, size_train=size1, size_test=size2, train_lis=train_yr, test_lis=test_yr, save=False)
params = save_param_values(race, rnd=3)
get_race_info()

models, baseline = ["M1", "M2", "M3"], "BL"
test_preds = get_test_preds(test, race, baseline=baseline, full=False)
test_preds

,id,dist,curr_pace,total_pace,finish,age,gender,year,male,alpha,age_t,agegroup,lvl,BL,M1,M2,M3
23464,138676,5K,2.981515,2.981515,2.907794,39,M,2024,1,1,0.39,2,1,-5.979950,10.308457,8.310653,11.933433
41746,156958,5K,2.364066,2.364066,2.264895,44,W,2024,0,1,0.44,3,1,-13.025250,15.186775,12.887106,12.917080
8633,123845,5K,3.750938,3.750938,3.492385,49,M,2024,1,1,0.49,3,1,-13.880217,-4.572654,-6.259327,-3.987579
3865,119077,5K,3.918495,3.918495,3.835909,39,M,2024,1,1,0.39,2,1,-3.863933,4.480524,2.851095,4.870059
26977,142189,5K,2.932551,2.932551,2.773250,34,W,2024,0,1,0.34,2,1,-13.775083,3.171796,1.151396,1.096302
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
388017,137374,40K,2.369668,2.952030,2.949049,59,M,2024,1,1,0.59,4,8,-0.240729,0.388859,1.229209,1.730413
417494,166851,40K,1.319958,1.684636,1.660763,24,W,2024,0,1,0.24,1,8,-6.000800,-5.097899,-4.202487,-4.899403
390499,139856,40K,2.530364,2.865124,2.860290,59,W,2024,0,1,0.59,4,8,-0.414835,0.229098,0.328546,0.570537
370866,120223,40K,3.548616,3.750938,3.727473,29,M,2024,1,1,0.29,1,8,-1.180217,-0.659235,-0.899638,-0.801641
385852,135209,40K,2.589332,3.030992,3.010488,39,M,2024,1,1,0.39,2,8,-1.580244,-0.963200,-0.580143,-0.333454

In [38]:
# import matplotlib.pyplot as plt
# pd.read_csv("stan_results/model2/params_bos.csv").describe().T
# params_tbl = pd.read_csv("analysis/tables/bos_params.csv")
# for col in params_tbl.columns:
#   if 'mean' in col:
#     plt.plot(params_tbl[col], label=col)

# # plt.plot(params_tbl["total_pace_mean"] + params_tbl["curr_pace_mean"])
# # plt.plot(params_tbl["total_pace_mean"] + params_tbl["curr_pace_mean"]+ params_tbl["alpha_mean"])
# plt.legend()
# plt.show()
# # plt.plot(pd.read_csv("analysis/tables/bos_params.csv")["curr_pace"])
# params_tbl["alpha_mean"]# + params_tbl["curr_pace_mean"]

In [39]:
test_list = [["BL", "M1"], ["BL", "M2"], ["BL", "M3"],["M1", "M2"], ["M1", "M3"], ["M2", "M3"]]
tbl2 = all_tests(test_preds, test_list, savename=f"analysis/tables/{race}_stattest.csv")
print(tbl2)

comp_model = "M3"
error_tbl = plots_for_race(test_preds, race, models, baseline, comp_model)
error_tbl

/Users/brandononyejekwe/Documents/Personal_Projects/Marathon_Predictor/utils.py:254: UserWarning: p-value floored: true value smaller than 0.001. Consider specifying `method` (e.g. `method=stats.PermutationMethod()`.)
  value = stats.anderson_ksamp([arr1, arr2]).pvalue

            KS Wilcoxon      CVM     AD
BL-M1  <0.0001  <0.0001  <0.0001  0.001
BL-M2  <0.0001  <0.0001  <0.0001  0.001
BL-M3  <0.0001  <0.0001  <0.0001  0.001
M1-M2  <0.0001  <0.0001  <0.0001  0.001
M1-M3  <0.0001  <0.0001  <0.0001  0.001
M2-M3  <0.0001  <0.0001  <0.0001  0.001
File saved: analysis/plots/chi_error_bar.jpg
File saved: analysis/tables/chi_error.csv
File saved: analysis/plots/chi_error_groups.jpg
File saved: analysis/plots/chi_error_gender_age.jpg

,BL,M1,M2,M3,pcnt_M1,pcnt_M2,pcnt_M3
5K,20.678817,16.640470,16.386504,16.542047,0.195289,0.207571,0.200049
10K,18.328082,14.324729,13.521348,13.541378,0.218427,0.262261,0.261168
15K,16.808693,12.928447,11.607248,11.837549,0.230848,0.309450,0.295748
20K,15.742424,11.115821,9.616436,9.407604,0.293894,0.389139,0.402404
25K,13.350323,9.252146,6.910848,6.992566,0.306972,0.482346,0.476225
30K,9.230582,6.659640,4.713631,4.761437,0.278524,0.489346,0.484167
35K,5.450820,3.952641,2.581718,2.592455,0.274854,0.526362,0.524392
40K,1.148686,1.104498,0.862640,0.843364,0.038469,0.249020,0.265801
Overall MAE,12.604000,9.511000,8.295000,8.335000,NaN,NaN,NaN
Overall $R^2$,0.888000,0.936000,0.941000,0.942000,NaN,NaN,NaN

In [40]:
# import pandas as pd
# params = pd.read_csv(f"stan_results/model3/params_{race}.csv", index_col="Unnamed: 0")
# params.describe().T[["mean", "std", "25%", "50%", "75%"]].round(4)

In [44]:
# train_full, test_full = get_data(racename=race, size_train=None, size_test=None, train_lis=train_yr, test_lis=test_yr, save=False)
# print(stats.ks_2samp(train["finish"], train_full["finish"]).pvalue)
# print(stats.anderson_ksamp([train["finish"], train_full["finish"]]).pvalue)
# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)
# print(stats.anderson_ksamp([test["finish"], test_full["finish"]]).pvalue)

# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)
# print(stats.ks_2samp(test["curr_pace"], test_full["curr_pace"]).pvalue)
# print(stats.ks_2samp(test["total_pace"], test_full["total_pace"]).pvalue)
# print(stats.ks_2samp(test["age"], test_full["age"]).pvalue)
# print(stats.ks_2samp(test["male"], test_full["male"]).pvalue)

In [42]:
mpreds2 = get_test_preds(test, race, baseline=baseline, full=True)
intervals_tbl = add_intervals_to_test(test_preds, mpreds2, models)
i_check, i_sizes = plot_interval_checks(intervals_tbl, models, save_name=race)

File saved: analysis/plots/chi_intervals
analysis/tables/chi_intsizes.csv
analysis/tables/chi_intcheck.csv