To create `train_all.csv` and `test_all.csv`, run `utils.py` first with the desired dataset size!

To update parameters using `train_all.csv`, run `store_params.r`.

In [1]:
import numpy as np
import pandas as pd
from utils import get_test_preds, save_param_values, get_race_info 
from plots import tests_and_plots, plot_params
np.random.seed(2025)

race = "all"
train_path, test_path = "processed_data/train_all.csv", "processed_data/test_all.csv"
train, test = pd.read_csv(train_path, index_col=0), pd.read_csv(test_path, index_col=0)
print(train.shape, test.shape)

test = test.sort_values(["lvl", "Race"]).reset_index()
params = save_param_values(rnd=3)
# get_race_info()

models, baseline = ["S1", "S2", "S3", "S4"], "BL"
test_preds = get_test_preds(test, race, baseline=baseline, full=False)
test_preds

(30000, 17) (30000, 17)

,index,id,dist,curr_pace,total_pace,finish,age,gender,year,male,...,lvl,Race,race_bos,race_chi,race_nyc,BL,S1,S2,S3,S4
0,9616,75254,5K,4.180602,4.180602,3.337948,26,M,2024,1,...,1,bos,1,0,0,-42.465933,-34.421293,-34.534244,-34.422390,-34.534074
1,7391,73029,5K,3.523608,3.523608,3.475986,53,M,2024,1,...,1,bos,1,0,0,-2.734317,8.576008,10.114176,8.565128,10.130755
2,24691,90329,5K,2.435460,2.435460,2.023644,50,M,2024,1,...,1,bos,1,0,0,-58.762217,-34.894093,-30.370233,-34.951872,-30.321812
3,13549,79187,5K,3.126954,3.126954,3.091662,42,F,2024,0,...,1,bos,1,0,0,-2.567317,11.808434,9.901038,11.787195,9.904085
4,6841,72479,5K,4.032258,4.032258,3.515078,42,M,2024,1,...,1,bos,1,0,0,-25.660667,-17.017674,-16.491971,-17.020441,-16.485638
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29995,396435,133679,40K,2.540650,3.115022,3.111955,38,M,2024,1,...,8,nyc,0,0,1,-0.222502,0.566191,0.724224,1.638052,1.648874
29996,430970,168214,40K,1.348800,2.148112,2.098106,37,M,2024,1,...,8,nyc,0,0,1,-7.802877,-6.708679,-6.194273,-2.627860,-2.698857
29997,423646,160890,40K,2.198769,2.340002,2.347296,31,W,2024,0,...,8,nyc,0,0,1,0.933887,1.950361,1.386955,1.172665,0.872202
29998,430851,168095,40K,1.833517,2.099848,2.102811,46,W,2024,0,...,8,nyc,0,0,1,0.471898,1.587497,1.118641,1.627469,1.603082
29999,394593,131837,40K,2.824859,3.204871,3.184288,45,M,2024,1,...,8,nyc,0,0,1,-1.418419,-0.649770,-0.472191,-0.300700,-0.208406

In [2]:
races_list = ["all", "bos", "nyc", "chi"]
comp_model = "S3"

tables_dict = tests_and_plots(test_data_full=test_preds, races_list=races_list,models=models, 
      baseline=baseline, full_preds=False, comp_model=comp_model, tests_list=["KS", "CVM", "Wilcoxon"])

tables_dict["bos"][1] # print(tables_dict["bos"][0])

File saved: analysis/tables/all_stattest.csv
File saved for all: error_bar.jpg, error.csv, error_groups.jpg, error_gender_age.jpg
File saved: analysis/tables/bos_stattest.csv
File saved for bos: error_bar.jpg, error.csv, error_groups.jpg, error_gender_age.jpg
File saved: analysis/tables/nyc_stattest.csv
File saved for nyc: error_bar.jpg, error.csv, error_groups.jpg, error_gender_age.jpg
File saved: analysis/tables/chi_stattest.csv
File saved for chi: error_bar.jpg, error.csv, error_groups.jpg, error_gender_age.jpg

,BL,S1,S2,S3,S4,pcnt_S1,pcnt_S2,pcnt_S3,pcnt_S4
5K,24.171200,15.601185,15.505271,15.607300,15.501204,0.354555,0.358523,0.354302,0.358691
10K,23.103396,14.465919,14.240571,13.058820,12.913292,0.373862,0.383616,0.434766,0.441065
15K,20.930999,12.127591,11.936243,10.839327,10.696188,0.420592,0.429734,0.482140,0.488979
20K,18.749028,10.953826,10.698324,9.061151,8.880130,0.415766,0.429393,0.516714,0.526369
25K,14.794152,8.307437,8.223413,6.495219,6.375261,0.438465,0.444144,0.560960,0.569069
30K,10.110389,6.237992,6.065180,4.301746,4.232856,0.383012,0.400104,0.574522,0.581336
35K,5.287103,3.775903,3.675816,2.620768,2.597894,0.285827,0.304758,0.504309,0.508636
40K,1.191427,0.981486,0.957024,0.718345,0.692410,0.176210,0.196741,0.397072,0.418840
Overall MAE,14.787000,9.045000,8.901000,7.824000,7.722000,NaN,NaN,NaN,NaN
Overall $R^2$,0.792000,0.898000,0.902000,0.907000,0.908000,NaN,NaN,NaN,NaN

In [3]:
tables_dict2 = tests_and_plots(test_data_full=test_preds, races_list=races_list,
        models=models, baseline=baseline, full_preds=True)

i_check, i_sizes = tables_dict2["all"]

File saved for all: intervals.jpg, sizes.csv, check.csv
File saved for bos: intervals.jpg, sizes.csv, check.csv
File saved for nyc: intervals.jpg, sizes.csv, check.csv
File saved for chi: intervals.jpg, sizes.csv, check.csv

In [4]:
# from scipy import stats
# from utils import get_data
# train_full, test_full = get_data(size_train=None, size_test=None, train_lis=[2021, 2022, 2023], test_lis=[2024], save=False)
# print(stats.ks_2samp(train["finish"], train_full["finish"]).pvalue)#, stats.anderson_ksamp([train["finish"], train_full["finish"]]).pvalue)
# print(stats.ks_2samp(test["finish"], test_full["finish"]).pvalue)#, stats.anderson_ksamp([test["finish"], test_full["finish"]]).pvalue)
# print()
# for col in ["finish", "curr_pace", "total_pace", "age", "male"]:
#     print(col, stats.ks_2samp(train[col], train_full[col]).pvalue)#, stats.anderson_ksamp([train[col], train_full[col]]).pvalue)
#     print(col, stats.ks_2samp(test[col], test_full[col]).pvalue)#, stats.anderson_ksamp([test[col], test_full[col]]).pvalue)

In [5]:
# params = pd.read_csv(f"stan_results/params_full3.csv", index_col="Unnamed: 0")
# params.describe().T[["mean", "std", "25%", "50%", "75%"]].round(4)
# plot_params("params3")